"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";
import "./arbeitsbereich.css";

type View = "ueberblick" | "nachweise" | "freigaben" | "massnahmen";
type TaskStatus = "Offen" | "In Arbeit" | "Erledigt";
type EvidenceStatus = "Aktuell" | "Prüfung nötig" | "Läuft bald ab";
type Task = { id: number; title: string; owner: string; due: string; status: TaskStatus; evidence?: string };
type Evidence = { id: number; title: string; area: string; level: string; validUntil: string; status: EvidenceStatus };
type Customer = { id: number; name: string; email: string; scope: string; shared: boolean };
type Dialog = "task" | "evidence" | "customer" | null;

const seedTasks: Task[] = [
  { id: 1, title: "MFA-Nachweis aktualisieren", owner: "IT-Sicherheit", due: "16. Sep. 2026", status: "In Arbeit", evidence: "MFA-Nachweis" },
  { id: 2, title: "Backup-Richtlinie bestätigen", owner: "Lena Bauer", due: "20. Sep. 2026", status: "Offen", evidence: "Backup-Richtlinie" },
  { id: 3, title: "Freigabe für Nordwerk prüfen", owner: "Einkauf", due: "27. Sep. 2026", status: "Offen" },
];
const seedEvidence: Evidence[] = [
  { id: 1, title: "ISMS-Leitlinie 2026", area: "Informationssicherheit", level: "Technisch belegt", validUntil: "30. Jun. 2027", status: "Aktuell" },
  { id: 2, title: "MFA-Nachweis", area: "Informationssicherheit", level: "Technisch belegt", validUntil: "16. Sep. 2026", status: "Prüfung nötig" },
  { id: 3, title: "Backup-Richtlinie", area: "Notfallmanagement", level: "Selbstauskunft", validUntil: "20. Sep. 2026", status: "Läuft bald ab" },
  { id: 4, title: "Lieferkettenerklärung", area: "Lieferkette", level: "Extern bestätigt", validUntil: "31. Dez. 2026", status: "Aktuell" },
];
const seedCustomers: Customer[] = [
  { id: 1, name: "Atlas Anlagenbau", email: "einkauf@atlas.example", scope: "12 Bereiche", shared: true },
  { id: 2, name: "Nordwerk", email: "supplier@north.example", scope: "8 Bereiche", shared: true },
  { id: 3, name: "Kern Industrie", email: "risk@kern.example", scope: "10 Bereiche", shared: false },
];

function Icon({ name }: { name: "grid" | "proof" | "share" | "task" | "plus" | "close" | "arrow" | "check" | "exit" }) {
  const props = { fill: "none", stroke: "currentColor", strokeWidth: 1.7, strokeLinecap: "round" as const, strokeLinejoin: "round" as const };
  if (name === "grid") return <svg viewBox="0 0 20 20" aria-hidden="true"><rect x="3" y="3" width="5" height="5" rx=".7" {...props} /><rect x="12" y="3" width="5" height="5" rx=".7" {...props} /><rect x="3" y="12" width="5" height="5" rx=".7" {...props} /><rect x="12" y="12" width="5" height="5" rx=".7" {...props} /></svg>;
  if (name === "proof") return <svg viewBox="0 0 20 20" aria-hidden="true"><path d="M5 2.8h7l3 3V17H5zM12 2.8V6h3" {...props} /><path d="m7.2 11 1.5 1.5 3.5-3.6" {...props} /></svg>;
  if (name === "share") return <svg viewBox="0 0 20 20" aria-hidden="true"><circle cx="5" cy="10" r="2" {...props} /><circle cx="15" cy="5" r="2" {...props} /><circle cx="15" cy="15" r="2" {...props} /><path d="m6.8 9 6.2-3M6.8 11l6.2 3" {...props} /></svg>;
  if (name === "task") return <svg viewBox="0 0 20 20" aria-hidden="true"><rect x="3" y="3" width="14" height="14" rx="2" {...props} /><path d="m6.5 10 2.2 2.2 4.8-4.8" {...props} /></svg>;
  if (name === "plus") return <svg viewBox="0 0 20 20" aria-hidden="true"><path d="M10 4v12M4 10h12" {...props} /></svg>;
  if (name === "close") return <svg viewBox="0 0 20 20" aria-hidden="true"><path d="m5 5 10 10M15 5 5 15" {...props} /></svg>;
  if (name === "arrow") return <svg viewBox="0 0 20 20" aria-hidden="true"><path d="M3 10h12M11 5l5 5-5 5" {...props} /></svg>;
  if (name === "check") return <svg viewBox="0 0 20 20" aria-hidden="true"><path d="m4.5 10.5 3.2 3.2 7.8-7.8" {...props} /></svg>;
  return <svg viewBox="0 0 20 20" aria-hidden="true"><path d="M8 3H4v14h4M11 6l4 4-4 4M6 10h9" {...props} /></svg>;
}

function Brand() { return <Link className="workspace-brand" href="/"><span><i /><i /><i /></span>prooflane</Link>; }
function Status({ value }: { value: TaskStatus | EvidenceStatus | "Freigegeben" | "Privat" }) { return <span className={`workspace-status status-${value.toLowerCase().replaceAll(" ", "-").replace("ü", "ue").replace("ä", "ae")}`}>{value}</span>; }

export default function ArbeitsbereichPage() {
  const [view, setView] = useState<View>("ueberblick");
  const [tasks, setTasks] = useState(seedTasks);
  const [evidence, setEvidence] = useState(seedEvidence);
  const [customers, setCustomers] = useState(seedCustomers);
  const [dialog, setDialog] = useState<Dialog>(null);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const openTasks = tasks.filter((task) => task.status !== "Erledigt");
  const attentionEvidence = evidence.filter((item) => item.status !== "Aktuell");
  const navigation: { id: View; label: string; icon: "grid" | "proof" | "share" | "task"; count?: number }[] = [
    { id: "ueberblick", label: "Überblick", icon: "grid" }, { id: "nachweise", label: "Nachweise", icon: "proof", count: evidence.length }, { id: "freigaben", label: "Freigaben", icon: "share", count: customers.filter((customer) => customer.shared).length }, { id: "massnahmen", label: "Maßnahmen", icon: "task", count: openTasks.length },
  ];
  function showNotice(message: string) { setNotice(message); }
  function closeDialog() { setDialog(null); setError(""); }
  function updateTask(id: number, status: TaskStatus) { setTasks((items) => items.map((item) => item.id === id ? { ...item, status } : item)); showNotice("Maßnahme gespeichert."); }
  function toggleCustomer(id: number) { setCustomers((items) => items.map((item) => item.id === id ? { ...item, shared: !item.shared } : item)); showNotice("Freigabe aktualisiert."); }
  function addTask(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const title = String(data.get("title") ?? "").trim(); const owner = String(data.get("owner") ?? "").trim(); const due = String(data.get("due") ?? ""); if (!title || !owner || !due) { setError("Titel, verantwortlich und Termin fehlen."); return; } setTasks((items) => [...items, { id: Date.now(), title, owner, due: new Intl.DateTimeFormat("de-DE", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(due)), status: "Offen", evidence: String(data.get("evidence") ?? "") || undefined }]); closeDialog(); showNotice("Maßnahme angelegt."); }
  function addEvidence(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const title = String(data.get("title") ?? "").trim(); const area = String(data.get("area") ?? ""); const validUntil = String(data.get("validUntil") ?? ""); if (!title || !area || !validUntil) { setError("Name, Bereich und Ablaufdatum fehlen."); return; } setEvidence((items) => [...items, { id: Date.now(), title, area, level: String(data.get("level") ?? "Selbstauskunft"), validUntil: new Intl.DateTimeFormat("de-DE", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(validUntil)), status: "Prüfung nötig" }]); closeDialog(); showNotice("Nachweis erfasst. Er bleibt privat bis zur Freigabe."); }
  function addCustomer(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const name = String(data.get("name") ?? "").trim(); const email = String(data.get("email") ?? "").trim(); if (!name || !email.includes("@")) { setError("Unternehmen und gültige E-Mail fehlen."); return; } setCustomers((items) => [...items, { id: Date.now(), name, email, scope: "Noch keine Bereiche", shared: false }]); closeDialog(); showNotice("Kunde angelegt. Freigabe bleibt zunächst privat."); }

  return <main className="workspace-shell"><aside className="workspace-sidebar" aria-label="Arbeitsbereich Navigation"><Brand /><div className="workspace-org"><span>H</span><div><b>HARTMANN Präzision</b><small>Zulieferer · DE</small></div></div><nav className="workspace-nav">{navigation.map((item) => <button key={item.id} className={view === item.id ? "is-active" : ""} onClick={() => setView(item.id)}><Icon name={item.icon} /><span>{item.label}</span>{item.count !== undefined && <b>{item.count}</b>}</button>)}</nav><div className="workspace-sidebar-bottom"><Link href="/anmelden"><Icon name="exit" />Abmelden</Link><small>Vorschau-Arbeitsbereich</small></div></aside><section className="workspace-main"><header className="workspace-header"><p>HARTMANN PRÄZISION <span>/</span> {navigation.find((item) => item.id === view)?.label}</p><div><span className="workspace-avatar">A</span><b>Anna</b></div></header><div className="workspace-content">{notice && <div className="workspace-notice" role="status"><Icon name="check" /><span>{notice}</span><button onClick={() => setNotice("")} aria-label="Hinweis schließen"><Icon name="close" /></button></div>}{view === "ueberblick" && <Overview tasks={openTasks} attentionEvidence={attentionEvidence} sharedCount={customers.filter((customer) => customer.shared).length} onView={setView} onUpdateTask={updateTask} />}{view === "nachweise" && <EvidenceView evidence={evidence} onAdd={() => setDialog("evidence")} />}{view === "freigaben" && <ApprovalsView customers={customers} onAdd={() => setDialog("customer")} onToggle={toggleCustomer} />}{view === "massnahmen" && <MeasuresView tasks={tasks} evidence={evidence} onAdd={() => setDialog("task")} onUpdate={updateTask} />}</div></section>{dialog === "task" && <WorkDialog title="Maßnahme anlegen" error={error} onClose={closeDialog}><TaskForm evidence={evidence} onSubmit={addTask} /></WorkDialog>}{dialog === "evidence" && <WorkDialog title="Nachweis erfassen" error={error} onClose={closeDialog}><EvidenceForm onSubmit={addEvidence} /></WorkDialog>}{dialog === "customer" && <WorkDialog title="Kunde hinzufügen" error={error} onClose={closeDialog}><CustomerForm onSubmit={addCustomer} /></WorkDialog>}</main>;
}

function Overview({ tasks, attentionEvidence, sharedCount, onView, onUpdateTask }: { tasks: Task[]; attentionEvidence: Evidence[]; sharedCount: number; onView: (view: View) => void; onUpdateTask: (id: number, status: TaskStatus) => void }) { return <><div className="workspace-page-title"><div><h1 className="text-balance">Arbeitsstand</h1><p className="text-pretty">Offene Punkte vor nächster Kundenfreigabe.</p></div><button className="workspace-primary" onClick={() => onView("massnahmen")}><Icon name="task" />Maßnahmen öffnen</button></div><section className="workspace-summary" aria-label="Zusammenfassung"><div><b>{tasks.length}</b><span>offene Maßnahmen</span></div><div><b>{attentionEvidence.length}</b><span>Nachweise prüfen</span></div><div><b>{sharedCount}</b><span>Kunden freigegeben</span></div></section><section className="workspace-section"><SectionHeading title="Nächste Maßnahmen" copy="Wählen Sie Status direkt in der Liste." action="Alle Maßnahmen" onClick={() => onView("massnahmen")} /><TaskTable tasks={tasks.slice(0, 4)} onUpdate={onUpdateTask} /></section><section className="workspace-section"><SectionHeading title="Nachweise mit Handlungsbedarf" copy="Neue Nachweise bleiben privat, bis Sie sie freigeben." action="Nachweise" onClick={() => onView("nachweise")} />{attentionEvidence.length ? <EvidenceTable evidence={attentionEvidence} /> : <EmptyState text="Keine Nachweise mit Handlungsbedarf." action="Nachweis erfassen" onAction={() => onView("nachweise")} />}</section></>; }
function SectionHeading({ title, copy, action, onClick }: { title: string; copy: string; action: string; onClick: () => void }) { return <div className="workspace-section-heading"><div><h2 className="text-balance">{title}</h2><p className="text-pretty">{copy}</p></div><button className="workspace-text-button" onClick={onClick}>{action} <Icon name="arrow" /></button></div>; }
function EvidenceView({ evidence, onAdd }: { evidence: Evidence[]; onAdd: () => void }) { return <><PageTitle title="Nachweise" copy="Dokumentiert, geprüft und gezielt freigegeben." action="Nachweis erfassen" icon="plus" onClick={onAdd} /><EvidenceTable evidence={evidence} /></>; }
function ApprovalsView({ customers, onAdd, onToggle }: { customers: Customer[]; onAdd: () => void; onToggle: (id: number) => void }) { return <><PageTitle title="Freigaben" copy="Kunden sehen nur bewusst freigegebene Bereiche." action="Kunde hinzufügen" icon="plus" onClick={onAdd} /><div className="workspace-table-wrap"><table className="workspace-table"><thead><tr><th>Kunde</th><th>E-Mail</th><th>Umfang</th><th>Status</th><th /></tr></thead><tbody>{customers.map((customer) => <tr key={customer.id}><td><b>{customer.name}</b></td><td>{customer.email}</td><td>{customer.scope}</td><td><Status value={customer.shared ? "Freigegeben" : "Privat"} /></td><td><button className="workspace-inline-action" onClick={() => onToggle(customer.id)}>{customer.shared ? "Freigabe stoppen" : "Freigeben"}</button></td></tr>)}</tbody></table></div></>; }
function MeasuresView({ tasks, evidence, onAdd, onUpdate }: { tasks: Task[]; evidence: Evidence[]; onAdd: () => void; onUpdate: (id: number, status: TaskStatus) => void }) { return <><PageTitle title="Maßnahmen" copy="Zuständigkeit, Termin und Status in einer Liste." action="Maßnahme anlegen" icon="plus" onClick={onAdd} />{tasks.length ? <TaskTable tasks={tasks} onUpdate={onUpdate} /> : <EmptyState text="Noch keine Maßnahmen angelegt." action="Maßnahme anlegen" onAction={onAdd} />}{evidence.length === 0 && <EmptyState text="Erfassen Sie zuerst einen Nachweis." action="Nachweis erfassen" onAction={onAdd} />}</>; }
function PageTitle({ title, copy, action, icon, onClick }: { title: string; copy: string; action: string; icon: "plus"; onClick: () => void }) { return <div className="workspace-page-title"><div><h1 className="text-balance">{title}</h1><p className="text-pretty">{copy}</p></div><button className="workspace-primary" onClick={onClick}><Icon name={icon} />{action}</button></div>; }
function TaskTable({ tasks, onUpdate }: { tasks: Task[]; onUpdate: (id: number, status: TaskStatus) => void }) { return <div className="workspace-table-wrap"><table className="workspace-table"><thead><tr><th>Maßnahme</th><th>Nachweis</th><th>Verantwortlich</th><th>Fällig</th><th>Status</th></tr></thead><tbody>{tasks.map((task) => <tr key={task.id}><td><b>{task.title}</b></td><td>{task.evidence || "—"}</td><td>{task.owner}</td><td>{task.due}</td><td><label className="workspace-select-label"><span className="sr-only">Status für {task.title}</span><select value={task.status} onChange={(event) => onUpdate(task.id, event.target.value as TaskStatus)}><option>Offen</option><option>In Arbeit</option><option>Erledigt</option></select></label></td></tr>)}</tbody></table></div>; }
function EvidenceTable({ evidence }: { evidence: Evidence[] }) { return <div className="workspace-table-wrap"><table className="workspace-table"><thead><tr><th>Nachweis</th><th>Bereich</th><th>Stufe</th><th>Gültig bis</th><th>Status</th></tr></thead><tbody>{evidence.map((item) => <tr key={item.id}><td><b>{item.title}</b></td><td>{item.area}</td><td>{item.level}</td><td>{item.validUntil}</td><td><Status value={item.status} /></td></tr>)}</tbody></table></div>; }
function EmptyState({ text, action, onAction }: { text: string; action: string; onAction: () => void }) { return <div className="workspace-empty"><p>{text}</p><button className="workspace-text-button" onClick={onAction}>{action} <Icon name="arrow" /></button></div>; }
function WorkDialog({ title, error, onClose, children }: { title: string; error: string; onClose: () => void; children: React.ReactNode }) { return <div className="workspace-dialog-layer"><dialog className="workspace-dialog" open onCancel={onClose} aria-labelledby="work-dialog-title"><div className="workspace-dialog-header"><h2 id="work-dialog-title" className="text-balance">{title}</h2><button onClick={onClose} aria-label="Dialog schließen"><Icon name="close" /></button></div>{children}{error && <p className="workspace-form-error" role="alert">{error}</p>}<p className="workspace-dialog-note">Änderungen gelten in dieser Vorschau nur während Sitzung.</p></dialog></div>; }
function TaskForm({ evidence, onSubmit }: { evidence: Evidence[]; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <form className="workspace-form" onSubmit={onSubmit}><label>Maßnahme<input name="title" required placeholder="z. B. MFA-Nachweis aktualisieren" /></label><label>Verantwortlich<input name="owner" required placeholder="Name oder Team" /></label><div className="workspace-form-grid"><label>Termin<input name="due" required type="date" /></label><label>Verknüpfter Nachweis<select name="evidence"><option value="">Nicht zugeordnet</option>{evidence.map((item) => <option key={item.id}>{item.title}</option>)}</select></label></div><button className="workspace-primary" type="submit">Maßnahme speichern</button></form>; }
function EvidenceForm({ onSubmit }: { onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <form className="workspace-form" onSubmit={onSubmit}><label>Name des Nachweises<input name="title" required placeholder="z. B. Netzwerksegmentierung" /></label><div className="workspace-form-grid"><label>Bereich<select name="area" defaultValue=""><option value="" disabled>Bitte wählen</option><option>Informationssicherheit</option><option>Notfallmanagement</option><option>Lieferkette</option></select></label><label>Stufe<select name="level"><option>Selbstauskunft</option><option>Technisch belegt</option><option>Extern bestätigt</option></select></label></div><label>Gültig bis<input name="validUntil" required type="date" /></label><button className="workspace-primary" type="submit">Nachweis erfassen</button></form>; }
function CustomerForm({ onSubmit }: { onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <form className="workspace-form" onSubmit={onSubmit}><label>Unternehmen<input name="name" required placeholder="Unternehmensname" /></label><label>Kontakt-E-Mail<input name="email" required type="email" placeholder="kontakt@unternehmen.de" /></label><button className="workspace-primary" type="submit">Kunde anlegen</button></form>; }
